export const materias = [
  {
    title: 'Ciencias',
    prof: 'Andressa',
    needed: 8.45,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Portugues',
    prof: 'Karina',
    needed: 8.05,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 2.5,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.5,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 0.5,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Arte',
    prof: 'Vivian',
    needed: 7.25,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Espanhol',
    prof: 'Natalia',
    needed: 7.15,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Historia',
    prof: 'Henry',
    needed: 6.9,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Matematica',
    prof: 'Rhaissa',
    needed: 6.9,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 2.5,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.5,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 0.5,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Redacao',
    prof: 'Camila',
    needed: 6.55,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Programacao',
    prof: 'Mauricio',
    needed: 6.5,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Fundo Quiz',
        date: '',
        value: 1.0,
        score: 1.0,
        status: true,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'PFE',
    prof: 'Rhaissa',
    needed: 6.5,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Ingles',
    prof: 'Natalia',
    needed: 6.45,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Geografia',
    prof: 'Henry',
    needed: 5.4,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
  {
    title: 'Ensino Religioso',
    prof: 'Valdirene',
    needed: 5.1,
    atividades: [
      {
        name: 'Prova 1',
        date: '',
        value: 3.0,
        score: 0,
        status: false,
      },
      {
        name: 'Prova 2',
        date: '',
        value: 4.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 1',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 2',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
      {
        name: 'Trabalho 3',
        date: '',
        value: 1.0,
        score: 0,
        status: false,
      },
    ],
  },
];
