export const materias = [
  {
    title: 'Ciencias',
    prof: 'Andressa',
    needed: 8.45,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '30/09',
        value: 3.0,
        score: 2.7,
        status: true,
        description:
          'Cap. 15, 16 e 17 - Biomas e seus impactos, ar e sua composição',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description:
          'Cap. 18, 19 e 20 - Terra, Noções de mecânica e termologia',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'SAEP',
      },
      {
        name: 'Trabalho 2',
        date: '07/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'Mostra Científica - Vídeo e Banner',
      },
      {
        name: 'Trabalho 3',
        date: 'Trimestre',
        value: 1.0,
        score: 1.0,
        status: true,
        description: 'Temas e produções de aula',
      },
    ],
  },
  {
    title: 'Portugues',
    prof: 'Karina',
    needed: 8.05,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '02/10',
        value: 2.5,
        score: 1.5,
        status: true,
        description:
          'Capítulos 17  (uso do meio e meia), 18, 19 e 20 (adjunto adverbial, complemento nominal e adjunto adnominal)',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 3.0,
        score: 0,
        status: false,
        description:
          'Capítulos 21, 22, 23 (uso do a, há, ah), 24, 25, 26 e 27. ',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'Simulados',
      },
      {
        name: 'Trabalho 2',
        date: '27/09',
        value: 1.0,
        score: 0.6,
        status: true,
        description: 'Leitura 1 - “O escaravelho do diabo”',
      },
      {
        name: 'Trabalho 3',
        date: 'Outubro',
        value: 1.0,
        score: 0,
        status: true,
        description: 'Leitura 2 - “O menino Nelson Mandela”',
      },
      {
        name: 'Trabalho 4',
        date: 'Novembro',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Leitura 3 - “Um dia na aldeia”',
      },
      {
        name: 'Trabalho 5',
        date: 'Ao longo do trimestre',
        value: 0.5,
        score: 0,
        status: false,
        description: 'Ciclos avaliativos',
      },
    ],
  },
  {
    title: 'Arte',
    prof: 'Vivian',
    needed: 7.25,
    atividades: [
      {
        name: 'P1 - Trabalho Trimestral',
        date: '26/09',
        value: 3.0,
        score: 3.0,
        status: true,
        description: 'trabalho plástico: Cubismo',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description:
          'Unidade 7: arte e as formas de imaginar Unidade 8: arte que se multiplica',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'SAEP',
      },
      {
        name: 'Trabalho 2',
        date: '31/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'trabalho plástico: gravura cordel',
      },
      {
        name: 'Trabalho 3',
        date: 'Trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'temas e produções em aula',
      },
    ],
  },
  {
    title: 'Espanhol',
    prof: 'Natalia',
    needed: 7.15,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '02/10',
        value: 3.0,
        score: 1.5,
        status: true,
        description:
          'Cap. 5 - ¿Dónde naciste?Conectores discursivos (p. 99)Pretérito Indefinido (p. 106 y 107) y marcadores temporales de pasado (p. 108)',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description:
          'Cap. 6 - De viaje Paisajes naturales (cap. 6)Estaciones del año (p. 126) Las comparaciones (p. 129) Expresiones de Baúl de palabras (p. 132) Verbos con zc en la primera persona de singular (p. 133 a 134)Hay/tiene (p. 140)',
      },
      {
        name: 'Trabalho 1',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Produção de texto (escrito ou oral) em espanhol.',
      },
      {
        name: 'Trabalho 2',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Trabalho realizado em aula',
      },
      {
        name: 'Trabalho 3',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Temas e produções de aula (planilha)',
      },
    ],
  },
  {
    title: 'Historia',
    prof: 'Henry',
    needed: 6.9,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '03/10',
        value: 3.0,
        score: 2.0,
        status: true,
        description:
          'Cap. 12 - Expansão marítimaCap. 13 - Os desafios do marCap. 14 - O que é colonizar',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description:
          'Cap. 15 - Os povos da AméricaCap. 16 - ÁfricaCap. 17 - Nativos e colonos na América',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'SAEP',
      },
      {
        name: 'Trabalho 2',
        date: '18/11',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Estudo dirigido dos capítulos 15, 16, 17.',
      },
      {
        name: 'Trabalho 3',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Tema, produção em aula e caderno',
      },
    ],
  },
  {
    title: 'Matematica',
    prof: 'Rhaissa',
    needed: 6.9,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '01/10',
        value: 2.5,
        score: 2.1,
        status: true,
        description:
          'Capítulos 15 ( ngulos), 16 (Razão), 17 (Proporção direta) e 18 (Proporção indireta).',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 3.0,
        score: 0,
        status: false,
        description: 'Capítulos 19 (Polígonos), 20 (Estudo do triângulo), 21 (Média), e 22 (Gráficos).',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'Simulados',
      },
      {
        name: 'Trabalho 2',
        date: 'Novembro',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Capítulos 23, 24 e 25 (Via Google Sala de Aula)',
      },
      {
        name: 'Trabalho 3',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Produções de aula',
      },
      {
        name: 'Trabalho 4',
        date: '',
        value: 1.5,
        score: 0,
        status: false,
        description: 'Catleaning e ciclos avaliativos',
      },
    ],
  },
  {
    title: 'Redacao',
    prof: 'Camila',
    needed: 6.55,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '30/9 a 04/10',
        value: 3.0,
        score: 1.9,
        status: true,
        description: 'scrita de uma crônica argumentativa',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description: '',
      },
      {
        name: 'Trabalho 1',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: '',
      },
      {
        name: 'Trabalho 2',
        date: 'trimestre',
        value: 2.0,
        score: 1.4,
        status: true,
        description: '',
      },
      
    ],
  },
  {
    title: 'Programacao',
    prof: 'Mauricio',
    needed: 6.5,
    atividades: [
      {
        name: 'P1 - Trabalho Questões de RPG ',
        date: '16/09 – 20/09 ',
        value: 3.0,
        score: 0,
        status: true,
        description: 'Lista de questões teóricas sobre jogos de RPG.',
      },
      {
        name: 'P2 - Trabalho Entrega de protótipo',
        date: '07/10 – 11/10 ',
        value: 4.0,
        score: 0,
        status: true,
        description: 'Entrega do protótipo do jogo',
      },
      {
        name: 'P3 - Trabalho Entrega do jogo ',
        date: '18/11 – 22/11',
        value: 4.0,
        score: 0,
        status: false,
        description: 'Entrega do projeto final.',
      },
    

    ],
  },
  {
    title: 'PEF',
    prof: 'Rhaissa',
    needed: 6.5,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '08/10',
        value: 3.0,
        score: 0,
        status: true,
        description: 'Continuação da tabela do planejamento familiar e orçamentos (em grupos e em aula).',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '26/11',
        value: 4.0,
        score: 0,
        status: true,
        description: 'Histórias em quadrinhos sobre Educação Financeira (individual, via google sala de aula.',
      },
      {
        name: 'Trabalho 1',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: true,
        description: 'Planejamento de uma viagem.',
      },
      {
        name: 'Trabalho 2',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Análise de Folhetos de Promoções.',
      },
      {
        name: 'Trabalho 3',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Discussão sobre Publicidade e Consumo.',
      },
    ],
  },
  {
    title: 'Ingles',
    prof: 'Natalia',
    needed: 6.45,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '30/09',
        value: 3.0,
        score: 2.4,
        status: true,
        description: 'Capítulos 5 e 6 do livro didático com ênfase no Present Perfect Tense',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description: 'Capítulo 8 do livro didático com ênfase nos verbos modais',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/10',
        value: 1.0,
        score: 0,
        status: true,
        description: 'SAEP',
      },
      {
        name: 'Trabalho 2',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Produção de aula',
      },
      {
        name: 'Trabalho 3',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Produção de aula',
      },
    ],
  },
  {
    title: 'Geografia',
    prof: 'Henry',
    needed: 5.4,
    atividades: [
      {
        name: 'P1 - Prova Parcial',
        date: '04/10',
        value: 3.0,
        score: 1.5,
        status: true,
        description: 'Cap. 14 - Estrutura etária do Brasil e do mundo Cap. 15 - População economicamente ativa: desafios atuais Cap. 16 - Medindo o desenvolvimento',
      },
      {
        name: 'P2 - Prova Parcial',
        date: '27/11 a 03/12',
        value: 4.0,
        score: 0,
        status: false,
        description: 'Cap. 17 - A desigualdade social e seus aspectos Cap. 18 - Conflitos no campo Cap. 19 - Conflitos na cidade',
      },
      {
        name: 'Trabalho 1',
        date: '09/09 e 24/1',
        value: 1.0,
        score: 0,
        status: true,
        description: 'SAEP',
      },
      {
        name: 'Trabalho 2',
        date: '22/11',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Estudo dirigido dos capítulos 17, 18, 19.',
      },
      {
        name: 'Trabalho 3',
        date: 'trimestre',
        value: 1.0,
        score: 0,
        status: false,
        description: 'Tema, produção em aula e caderno',
      },
    ],
  },
  {
    title: 'Ensino Religioso',
    prof: 'Valdirene',
    needed: 5.1,
    atividades: [
      {
        name: 'P1 - Trabalho Trimestral - ',
        date: '27/09',
        value: 3.0,
        score: 2.0,
        status: true,
        description: 'Cap. 5 - Líderes Religiosos',
      },
      {
        name: 'P2 - Trabalho Trimestral',
        date: '22/11',
        value: 4.0,
        score: 3.7,
        status: true,
        description: 'Cap. 6 - O diálogo entre as religiões - pag 89, 90, 91, 92 e 93',
      },
      {
        name: 'Trabalho 1',
        date: '13/09',
        value: 1.5,
        score: 1.3,
        status: true,
        description: 'Apresentação dos símbolos pessoais',
      },
      {
        name: 'Trabalho 2',
        date: '08/11',
        value: 1.5,
        score: 1.3,
        status: false,
        description: 'Cap. 5 - Líderes Religiosos - pag. 75, 79 e 82',
      },
      
    ],
  },
];
